# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_text', models.CharField(max_length=200)),
                ('base_cmd', models.CharField(max_length=200)),
                ('flags', models.CharField(max_length=200)),
                ('args', models.CharField(max_length=200)),
                ('line_no', models.IntegerField(default=0)),
            ],
        ),
    ]
